version: "3.1"
services:
    www:
        container_name: www
        build: .
        ports: 
            - "8001:80"
        volumes:
            - ./www:/var/www/html/
        networks:
            - default
    db:
        container_name: db
        image: mysql:8.0
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: soutenance
            MYSQL_USER: user
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root 
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - 8000:80
volumes:
    persistent: